# Generated by Django 5.0.6 on 2024-06-23 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenovationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Место ремонта')),
            ],
        ),
        migrations.CreateModel(
            name='BonusProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('consent_to_data_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('man', 'Мужской'), ('wom', 'Женский')], default=None, max_length=3, null=True, verbose_name='Ваш пол')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('has_children', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=None, max_length=3, null=True, verbose_name='Наличие детей')),
                ('renovation_plan', models.CharField(choices=[('already_ongoing', 'Уже идет'), ('starting_soon', 'Скоро приступаем'), ('within_half_year', 'В течение полугода'), ('within_year', 'В течение года')], default=None, max_length=100, null=True, verbose_name='Планируется ли ремонт?')),
                ('ren_planned', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=None, max_length=3, null=True, verbose_name='Планируется ли ремонт')),
                ('subscription_consent', models.BooleanField(default=False, verbose_name='Согласие на рассылку')),
                ('renovation_location', models.ManyToManyField(blank=True, to='istok_app.renovationlocation', verbose_name='Где планируется ремонт?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
