# Generated by Django 5.0.6 on 2024-06-30 07:15

import django.db.models.deletion
import istok_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istok_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bathroom', 'Ванная'), ('wardrobe', 'Гардероб'), ('racks', 'Стеллажи'), ('hallways', 'Прихожие'), ('kitchen', 'Кухни'), ('dresser', 'Комоды'), ('children', 'Детские')], default=None, max_length=100, null=True, verbose_name='Категории')),
                ('image', models.ImageField(upload_to=istok_app.models.Category.image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to=istok_app.models.Product.main_image_upload_to, verbose_name='Главное изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='istok_app.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=istok_app.models.ProductImage.image_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images_set', to='istok_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='products_with_additional_images', to='istok_app.productimage'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
